Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1114841-sedona-31 pull request #11
Opened 2021-07-01 17:00 UTC by valkiboy

Не понял как сделать полоску разделяющую фильтры "от" и "до".
Подскажите в какую сторону двигаться. Просто полосу и потом позиционировать или это бордер. Как лучше?

2021-07-01 17:02 UTC, valkiboy reviewed
Не понял как сделать полоску разделяющую фильтры "от" и "до".
Подскажите в какую сторону двигаться. Просто полосу и потом позиционировать или это бордер. Как лучше?

2021-07-02 14:27 UTC, andreysgra requested changes
Ваш вопрос: "_Не понял как сделать полоску разделяющую фильтры "от" и "до"._": проще всего сделать через псевдо элемент общего блока `filter-interval`. Например, как сделано здесь:
![image](https://user-images.githubusercontent.com/17790771/124287004-3653d200-db58-11eb-8f57-edd655a50335.png)

---

Внешний вид этих кнопок
![image](https://user-images.githubusercontent.com/17790771/124287097-4cfa2900-db58-11eb-8c5f-42cf537dbccf.png)
не соответствует макету. Текс по центру относительно вертикали проще всего разместить за счёт верхнего и нижнего паддинга ссылки: высота должна формироваться не свойством `height` (это решение неудачное - стоит изменить размер шрифта или перенести текст на вторую строку - всё сломается), а высотой контента (в данном случае это высота линии текста в кнопке - `line-height` (она уже задана в ссылке)) и свойствами `padding-top` и `padding-bottom`.

---

Есть ошибка валидации HTML страницы каталога:
![image](https://user-images.githubusercontent.com/17790771/124287729-0953ef00-db59-11eb-96cc-d30a0309ebd9.png)

2021-07-02 14:27 UTC, andreysgra commented on catalog.html
> +            <li><a href="" class="map-state">Карта штата</a></li>
А какой смысл задавать разные классы ссылкам в меню? Они идентичны.

2021-07-02 14:27 UTC, andreysgra commented on catalog.html
> +                  <li class="filter-option infrastructure-WI-FI">
Здесь такой же вопрос, что и выше - про классы. `margin-left` у всех элементов одинаков (если есть где-то отличия в пиксель - это погрешность макета и под неё не нужно подстраиваться), `margin-bottom` тоже одинаков, а у последнего элемента его нужно обнулить через `:nth-child`. Так же есть замечательная технология `grid`, которая позволяет забыть об использовании (и соответственно обнулении у последнего элемента) внешних отступов. Если родительский блок сделать `grid` контейнеров, то можно использовать свойства `column-gap` и `row-gap` для задания необходимых отступов.

2021-07-02 14:27 UTC, andreysgra commented on catalog.html
> +                  <li class="filter-option housing-type-apartments">
И здесь вопрос по наименованию классов идентичных элементов.

2021-07-02 14:27 UTC, andreysgra commented on catalog.html
> +                      <div class="filter-range-handle max"></div>
Не знаю, что там рисуют в демках и что по этому поводу говорят на лекции, но здесь уместны кнопки (так, как было у вас раньше) в качестве элементов управления, а не `div`. Это моё видение и я не обязываю вас исправлять, просто пишу к сведению.

2021-07-03 08:38 UTC, merged